# Feature Extraction - PCA

##### PCA 알고리즘 - 출처 : 단단한 머신러닝 챕터 10
**입력** 
- 샘플 세트 D = {x_1, x_2, .... , x_m}. 저차원 공간 차원수 d'

**과정** 
1. 모든 샘플에 대해 정규화 진행 :$x_i <= x_i - \frac{1}{m}\sum_{i=1}^m x_i$ 
2. 샘플의 공분산 행렬 $XX^T$
3. 공분산 행렬 XX^T에 대하여 고윳값 분해 진행 
4. 최대 크기의 d'개 고윳값에 대응하는 특징 벡터 $w_1, w_2, ...w_{d^'}$를 취한다. 

**출력**
투영 행렬 $W^* =(w_1, w_2, ..., w_{d^'})$


In [1]:
# 데이터 사용 및 라이브러리 설치 

import numpy as np
import pandas as pd 

from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression 

boston = load_boston()
X = boston.data 
y = boston.target

C:\Users\PC\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e

##### PCA 알고리즘 - 출처 : 단단한 머신러닝 챕터 10
**입력** 
- 샘플 세트 D = {x_1, x_2, .... , x_m}. 저차원 공간 차원수 d'
> X : 데이터 세트  
> y : 타겟 데이터 
> n : 데이터의 개수 


**과정** 
1. 모든 샘플에 대해 정규화 진행 :$x_i <= x_i - \frac{1}{m}\sum_{i=1}^m x_i$ 
2. 샘플의 공분산 행렬  𝑋𝑋𝑇

**구현해야하는 것**
- 정규화 :  각 x_i 데이터 속성별로 mean(x_i) 값을 빼주기 
- 각 속성별 평균 구하기 

**필요로 하는 것**
- X 

**함수의 형태**
- def normarization(self, metrix) :



In [2]:
class PCA() : 
    def __init__(self, X, y) : 
        self.X = X
        self.y = y 
        self.n = np.shape(X)[0] 
        self.m = np.shape(X)[1]
    
    def normarization(self) : 
        mean_X = np.mean(self.X, axis=0)
        return np.array(self.X)-mean_X
    
    def cov(self,metrix): 
        return np.dot(np.array(metrix).T, np.array(metrix))
        

In [3]:
test = PCA(X,y)
b = test.normarization()
test.cov(b)

array([[ 3.73632220e+04, -2.03090578e+04,  1.21161311e+04,
        -6.16648645e+01,  2.11894916e+02, -6.69144114e+02,
         4.31296878e+04, -3.47274438e+03,  2.36581193e+04,
         4.26634877e+05,  2.72666205e+03, -1.52702817e+05,
         1.41330148e+04],
       [-2.03090578e+04,  2.74688091e+05, -4.31333873e+04,
        -1.27727273e+02, -7.05054841e+02,  2.58181927e+03,
        -1.88820282e+05,  1.64777985e+04, -3.19910909e+04,
        -6.24409136e+05, -9.98716818e+03,  1.88729308e+05,
        -3.47354336e+04],
       [ 1.21161311e+04, -4.31333873e+04,  2.37675434e+04,
         5.53827470e+01,  3.06572215e+02, -9.53418066e+02,
         6.28795211e+04, -5.16518922e+03,  1.79527355e+04,
         4.20846947e+05,  2.87451252e+03, -1.12907777e+05,
         1.49380365e+04],
       [-6.16648645e+01, -1.27727273e+02,  5.53827470e+01,
         3.25790514e+01,  1.35557292e+00,  8.22379644e+00,
         3.12378458e+02, -2.67866941e+01, -8.22924901e+00,
        -7.69300395e+02, -3.37436759e

#### 3. 공분산 행렬 XX^T에 대하여 고윳값 분해 진행
#### 4. 최대 크기의 d'개 고윳값에 대응하는 특징 벡터  w_1, w_2, ...w_{d^'} 를 취한다.

**과정** 
1. 고윳값 분해를 통해 고윳값과 고유벡터를 구할 것 
2. 구한 고윳값의 크기에 따라 내림차순으로 정렬할 것 
3. 고윳값이 0인 경우는 제외하며, 입력값으로 입력한 고윳값 개수에 따라 추출하기
4. 선택한 고윳값에 따라 분산이 얼마나 설명되는지 계산하기 

**구현해야하는 것**
- 고윳값 분해 
- 정렬할 것 
- 현재 분산 설명력 : 현 고윳값 / 전체 고윳값의 합

**필요로 하는 것**
- num : 적용할 고윳값의 개수 
- metrix : 고윳값 분해를 할 metrix 


**함수의 형태**
- def eigen(self, metrix): => 내림차순으로 정렬된 고윳값 list, 고윳값과 매칭되는 고유벡터 list

- def select_eigen(self, num, metrix) : => num 개수에 맞춰 고유 벡터 list 및 현재 분산 설명력 제시 

In [4]:
# 최종본 

class PCA() : 
    def __init__(self, X, y) : 
        self.X = X
        self.y = y 
        self.n = np.shape(X)[0] 
        self.m = np.shape(X)[1]
    
    def normarization(self) : 
        mean_X = np.mean(self.X, axis=0)
        return np.array(self.X)-mean_X
    
    def cov(self,metrix): 
        return np.dot(np.array(metrix).T, np.array(metrix))
        
    def eigen(self, metrix):
        eigenvalue, eigenvector = np.linalg.eig(metrix)
        eigenvector_lst = []
        index = np.argsort(eigenvalue)[::-1]
        for i, num in enumerate(index) : 
            eigenvector_lst.append(eigenvector[i, :])
        return np.take(eigenvalue, index), np.array(eigenvector_lst)
    
    def select_eigen(self, num) : 
        if num > self.m : 
            return print("Please lower num under", self.m)
            
        norm_metrix = self.normarization()
        cov_metrix = self.cov(norm_metrix)
        eigenvalue, eigenvector = self.eigen(cov_metrix)
        return eigenvector[:num, :], sum(eigenvalue[:num])/sum(eigenvalue)


In [7]:
test = PCA(X,y)
test.select_eigen(4)

(array([[ 2.92973218e-02,  6.66847277e-03,  1.14793645e-02,
          2.71309632e-02, -9.52338065e-01,  1.69050862e-01,
          2.16220534e-01,  1.24410586e-01, -1.37713177e-02,
         -1.66179883e-02, -1.99666297e-03, -1.99499182e-03,
         -5.12974614e-04],
        [-4.35898000e-02,  1.17564821e-03, -6.32897481e-01,
          7.68058991e-01,  5.67213995e-03, -4.68215380e-02,
          3.51598379e-02, -5.13731838e-02, -2.35075239e-02,
          3.06891846e-02,  5.51190327e-03,  1.93735139e-04,
         -1.27249747e-04],
        [ 2.83309382e-02, -4.94975624e-03,  8.83403603e-02,
         -1.28007210e-02,  5.71048624e-02, -3.43651593e-01,
          7.85948681e-01, -4.90776545e-01, -3.52993231e-02,
         -9.80914287e-02, -1.78544855e-02,  8.11846520e-03,
          4.24115064e-03],
        [-5.55846350e-05, -1.02678850e-04,  9.75320360e-04,
          8.54389584e-04,  2.16905859e-03,  3.50007555e-03,
          5.10632892e-03, -1.13540624e-02,  1.78071403e-02,
          1.5794441

In [36]:
a = np.array([[1,2,3],[2,6,3],[7,1,3]])


array([3, 2, 1])